### ISSUE TITLE
Error : Cannot find file with extension 'bcor'! When Running FINEMAP with finemapper.py

### ISSUE THREAD

**Issue by johnacurtin** [omerwe/polyfun#82] opened 2022-01-31 11:51 UTC
Hi, 
I sometimes get the error 
**Cannot find file with extension 'bcor'!**
when I run finemapper.py using the finemap method. When I run same region using the susie method i do not get any error. Any advice would be appreciated. I do not always get this error and it would be good to know why I get this error and how to get around it.

python finemapper.py \
    --geno bfile.1 \
    --sumstats S-LDSC.1.snpvar_ridge_constrained.gz \
    --n 10000 \
    --chr 1 \
    --start startnumber \
    --end stopnumber \
    --method finemap \
    --finemap-exe ${FINEMAP} \
    --max-num-causal 2 \
    --cache-dir ${LD_cache_finemap} \
    --out FINEMAP.S-LDSC.1.out.gz \
    --allow-missing \
    --verbose

Many thanks
John

**Comment by omerwe** [comment] 2022-01-31 16:57
Hi @johnacurtin,

Thanks for the bug report. This error only occurs with FINEMAP because only FINEMAP uses .bcor files. To help diagnose this issue, can you please help me understand it better?

Does this happen consistently for some runs but not for others? Or does it sometimes happen and sometimes not when you run it on the exact same input? If it's the former, can you please send a reproducible end-to-end example so that I can try it out? If it's the latter, it's probably a file-system related issue. Perhaps you're using an NFS filesystem and it takes some time for newly created files to become available? I guess you could test this by running a small use case on your personal laptop, and see if the problem repeats there.

**Comment by johnacurtin** [comment] 2022-02-01 16:04
Dear Omer,
I am currently re-running exactly the same FINEMAP runs to see if the same error occurs reproducibly. With the same input files and regions.
I will let you know the outcome tomorrow.
Regards
John

**Comment by johnacurtin** [comment] 2022-02-02 13:46
Dear Omer,
I have rerun this and it is the 2nd option i.e. :
it sometimes happens and sometimes not when I run it on the exact same input.

With regards to your question about NFS; then I type
nfsstat –m
it indicates: vers=3, mountvers=3 so it would appeat to be using NFS.

Generally we are using CentOS Linux 7 and Red Hat 4.8.5-39
To help me try to track this down. Do these bcor files get saved on the fly to a temporary folder. Is there a way to figure out where they go so I have something more concrete to query IT?
Many thanks
John


From: John Curtin
Sent: 01 February 2022 16:04
To: omerwe/polyfun ***@***.***>; omerwe/polyfun ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [omerwe/polyfun] Error : Cannot find file with extension 'bcor'! When Running FINEMAP with finemapper.py (Issue #82)

Dear Omer,
I am currently re-running exactly the same FINEMAP runs to see if the same error occurs reproducibly. With the same input files and regions.
I will let you know the outcome tomorrow.
Regards
John

**Comment by omerwe** [comment] 2022-02-02 14:18
Hi @johnacurtin,

To answer your specific question, the files are created in the directory that you specify to `--cache-dir`.

However, looking at your original command again, it seems to me that the code doesn't require .bcor files (because you use a plink rather a bgen file as input). Is this correct? If it is, I'm not sure what's going on... 
When you specify plink files, the code should create a text file representing the LD matrix, rather a bcor file. 


Can you please send the full error message that you get, with the full stack trace?

**Comment by omerwe** [comment] 2022-02-02 16:20
Hi John,

Can you please add the following two flags to your command?
1. `--verbose` 
2. `--finemap-dir`  `<name of directory>`  (please provide some directory name that will be created to store all the FINEMAP output files)

After you add these, can you please rerun the command and copy-paste (1) the output; (2) the list of files created in the directory you specified for `finemap-dir`; and (3) the contents of the .master file that should have been created inside this directory?

This will give me more details. What I meant about stack trace is to simply copy-paste all the output that you get...

There's no need to create a ped file, I don't think it's related to the issue.

**Comment by johnacurtin** [comment] 2022-02-03 13:17
Dear Omer,
Many thanks again for your time. Firstly again the runs that worked and did work is still inconsistent.
Note: I needed to truncate path info as this gets posted to a website.

(1) the output (for a failed run)
[INFO]  Loading sumstats file...
[INFO]  Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[INFO]  NumExpr defaulting to 8 threads.
[INFO]  Loaded sumstats for 232110 SNPs in 2.44 seconds
[INFO]  Saving FINEMAP files to directory: /FinalOutDir/18_70379807_73379807/
[WARNING]  The available cached LD file was ignored because it does not contain data for all the SNPs in the locus
[INFO]  Computing LD from plink fileset /PolyFunAnnotations/bfiles/bfile.18 chromosome 18 region 70379807-73379807
[INFO]  Found 10462 SNPs in target region. Computing LD in 1 chunks...
[INFO]  Done in 3.78 seconds
[INFO]  Saving LD file /PolyFunAnnotations/LD_cache_finemap/bfile.18.18.70379807.73379807.npz
[INFO]  Done in 21.00 seconds
[WARNING]  233 variants with sumstats were not found in the LD file and will be omitted (please note that this may lead to false positives if the omitted SNPs are causal!)
[INFO]  Flipping the effect-sign of 5725 SNPs that are flipped compared to the LD panel
[INFO]  Starting functionally-informed FINEMAP fine-mapping for chromosome 18 BP 70379807-73379807 (10430 SNPs)
[INFO]  Running FINEMAP...
[INFO]  Command: /FINEMAP_Prog_Dir/finemap_v1.4_x86_64/finemap_v1.4_x86_64 --in-files /FinalOutDir/18_70379807_73379807/finemap.master --sss --force-n-samples --log /FinalOutDir/18_70379807_73379807/finemap.log --n-causal-snps 2 --std-effects --prior-snps
[INFO]  done in 5.86 seconds
[ERROR]  Error : Cannot find file with extension 'bcor'!

(2) the list of files
finemap.config
finemap.ld
finemap.log_sss
finemap.master
finemap.snp
finemap.z

Please note: for runs that worked there is also the files finemap.cred1 and finemap.cred2

(3) the contents of the .master
z;snp;config;cred;log;n_samples;ld
/FinalOutDir/18_70379807_73379807/finemap.z;/FinalOutDir/18_70379807_73379807/finemap.snp;/FinalOutDir/18_70379807_73379807/finemap.config;/FinalOutDir/18_70379807_73379807/finemap.cred;/FinalOutDir/18_70379807_73379807/finemap.log;10000;/FinalOutDir/18_70379807_73379807/finemap.ld

the parameters that I used
cd ${FinalOutDir}
mkdir 18_70379807_73379807  ## the --finemap-dir creates files with the same names so I created a new temp dir for each region
cd ${polyfunProgrammeDir}

python finemapper.py \
    --geno ${bfilesDir}bfile.18 \
    --sumstats ${LDSCNonparout}PolyFunApproach3_S-LDSC_non-parametric.18.snpvar_constrained.gz \
    --n 10000 \
    --chr 18 \
    --start 70379807 \
    --end 73379807 \
    --method finemap \
    --finemap-exe ${FINEMAP} \
    --max-num-causal 2 \
    --cache-dir ${LD_cache_finemap} \
    --finemap-dir ${FinalOutDir}18_70379807_73379807/ \
    --out ${FinalOutDir}finemapped.FINEMAP.S-LDSC_nonparametric.2Feb2022.18.70379807.73379807.gz \
    --allow-missing \
    --verbose

Many thanks again for your time.
John

**Comment by johnacurtin** [comment] 2022-02-04 12:01
Dear Omer,
Thanks again for your time.

I ran the example finemap code several times:
/FINEMAP_Prog_Dir/finemap_v1.4_x86_64/finemap_v1.4_x86_64 --in-files /FinalOutDir/18_70379807_73379807/finemap.master --sss --force-n-samples --log /FinalOutDir/18_70379807_73379807/finemap.log --n-causal-snps 2 --std-effects --prior-snps

When I run with the above code I get the same thing. For runs that do not work  it generates the error: Error : Cannot find file with extension 'bcor'!
Also the files finemap.config, finemap.log_sss, finemap.snp get overwritten (0 bytes all three)

For runs that do not generate any error using just the FINEMAP command its modifies the files
finemap.config, finemap.log_sss, finemap.snp finemap.cred1 finemap.cred1 and there is something in all those files. But no other output gets generated i.e. no polyfun style finemap output or log.

I wonder if I need bcor files. I know we do not specify but the  I see that the --force-n-samples flag seems to have something to do with bcor.

Regards
John

**Comment by omerwe** [comment] 2022-02-04 12:52
Hi John,

Just to be 100% sure, do you run the exact same command (on the exact same input files) and only sometimes get the error message? In the answer is yes then it's definitely a bug in the FINEMAP software, since this command simply runs the FINEMAP software and has nothing to do with the code of PolyFun.

You could try reaching out to the author of FINEMAP (Christian Benner), though I don't know if he's still maintaining the software. 

Alternatively, you could decide to simply use SuSiE, which we found to be just as good or better across many experiments.

Best,

Omer

**Comment by omerwe** [comment] 2022-02-08 08:44
Hi John,

Thanks for confirming this. As I wrote above, this is outside the scope of PolyFun, so I can't help with this. Christian Benner might be able to help, or you could focus on using SuSiE, which from our experience is just as good.

If you confirm this is a FINEMNAP problem, can we close the issue?

**Comment by jdblischak** [comment] 2022-02-16 18:52
I also observe this behavior when trying to use PolyFun+FINEMAP with insample genotypes from Plink files. Strangely, it affected the majority of the loci I was attempting to fine-map, but not all of them. I tried troubleshooting back in October, but got frustrated and had to move on to other projects.

> It's very surprising --- the code doesn't have anything to do with bcor files (they're only relevant for bgen input files).

Exactly. I was/am confused about the error.

> can you please send a reproducible end-to-end example so that I can try it out?

In case it could be a potential clue, when I was trying to debug the issue, I couldn't even import the LD matrix created from the Plink genotypes. It failed the following assertion:

https://github.com/omerwe/polyfun/blob/29c37eb8ededdda195b2706b903d89691930ff40/finemapper.py#L71

So maybe there is an issue with the newly created insample LD matrix, and then PolyFun executes FINEMAP with flags such that it expect a `.bcor` file. Just an idea. It's been a few months since I dived deep into this, so it's not currently fresh in my mind.

**Comment by omerwe** [comment] 2022-02-16 21:10
@jdblischak thanks for the update. As written at the end of this thread, we isolated the problem to FINEMAP itself. @johnacurtin reports that when he runs FINEMAP directly (not using the PolyFun scripts), he occasionally (but not always) gets the same error message, when running it multiple times on the exact same input files.

Hence it looks like there's a strange non-deterministic bug with FINEMAP itself...

**Comment by mkoromina** [comment] 2022-03-01 16:21
Hi @omerwe and @jdblischak , just a quick message to ask you whether this issue has been resolved or whether it is better to contact the authors of Finemap. I am running polyfun-finemap by using plink files in the --geno flag and I also get the same error message. For a few of loci to be fine-mapped, it runs fine but for the majority, it crushes with the above-mentioned error message (i.e., cannot fine extension 'bcor').  Thanking you in advance!

**Comment by jdblischak** [comment] 2022-03-02 16:03
> whether this issue has been resolved

I'm not aware of a workaround

> or whether it is better to contact the authors of Finemap. 

I just sent Christian an email. I'll let you all know if I learn anything

**Comment by johnacurtin** [comment] 2022-03-02 16:43
I also have tried emailing Christian, on two different email addresses, but I get an undeliverable email response. I am happy to run any tests that Christian might suggest if that would help matters.

**Comment by jdblischak** [comment] 2022-03-03 19:38
I suspect the FINEMAP error is produced by numerical instability in the LD matrix produced by numpy.

@johnacurtin and @mkoromina Could you please follow [these instructions](https://github.com/omerwe/polyfun/issues/63#issuecomment-1057461213) to update your local PolyFun installation to use the latest changes in my PR #90, and then re-run your examples? Make sure to delete any existing LD matrix files so that they are recreated using 64bit floating point numbers.

**Comment by omerwe** [comment] 2022-03-04 10:30
Hi all, I just accepted the pull request, so once you git pull from the main repo this problem should (hopefully!) be fixed. Please let me know if it's indeed fixed!

**Comment by jdblischak** [comment] 2022-03-04 20:21
I confirmed that this fixed the problem I was having. Hopefully it will work for @johnacurtin and @mkoromina as well 🤞

**Comment by mkoromina** [comment] 2022-03-04 21:51
Hi @jdblischak thank you so much for this! I will try your instructions and test whether this issue occurs within the weekend and get back to you by latest this Tuesday. The reason for my slight delay will be the fact that I am already running some jobs with another polyfun python script, so I'd wish for them to be completed and then to try the git pull to amend these issues! Your quick reply is truly appreciated!

**Comment by mkoromina** [comment] 2022-03-07 15:18
Hi again! Just a quick update from me: I updated polyfun with the git pull command and submitted today a couple of jobs (polyfun-finemap pipeline and usage of genotype plink files with the --geno flag) and they are running fine  so far.  Thank you very much once again for your prompt look into this matter!

**Comment by jdblischak** [comment] 2022-03-07 15:40
FYI Christian Benner also just released FINEMAP 1.4.1. Now instead of getting the confusing error about a missing bcor file, you would receive a more informative error message, e.g.:

> Error : Correlation 1.0000 between SNP 791 and SNP 798 in file 'finemap.ld' is not between -1.0 and 1.0!

And as discussed above, if you receive this error message, the solution is to `git pull` and recreate the LD matrix.

http://christianbenner.com/
http://christianbenner.com/finemap_v1.4.1_x86_64.tgz
http://christianbenner.com/finemap_v1.4.1_MacOSX.tgz

**Comment by omerwe** [comment] 2022-03-07 21:06
Great, I'll update the install instructions to point to this new version!
Can we close the issue?

**Comment by mkoromina** [comment] 2022-03-07 22:05
Hi @omerwe, I can confirm from my end that everything runs fine with this amendment! Thanks again a lot!

**Comment by omerwe** [comment] 2022-03-08 21:20
Great, I'll close the issue for now. Please feel free to reopen it if you run into any more issues with the latest version.

**Closed by omerwe** 2022-03-08 21:20 UTC

**Comment by jerome-f** [comment] 2022-08-12 03:17
This might be relevant in this thread, when using in sample LD the --force-n-samples needs to be unset, it is only needed in case the # of samples in the GWAS differ from the number of samples in the BCOR file. This seems specific to bcor files. I am not sure how it translated if we use LD from .npz, I've reached out to Christian about this will keep this thread posted and create a PR if need be.

**Comment by omerwe** [comment] 2022-08-12 15:41
Thanks @jerome-f, please keep us posted!
