### ISSUE TITLE
Exact path to UKBB LD files on new google cloud space

### ISSUE THREAD

**Issue by nievergeltlab** [omerwe/polyfun#155] opened 2023-04-20 18:55 UTC
The UKBB LD files referenced by this program (e.g. https://data.broadinstitute.org/alkesgroup/UKBB_LD/chr1_46000001_49000001.gz) have been moved to google cloud - https://console.cloud.google.com/storage/browser/broad-alkesgroup-public-requester-pays

However I can't find the sub directory where these are stored, could you please let me know?

thanks
Adam

**Comment by nievergeltlab** [comment] 2023-04-21 21:22
I see, their website says, "UKBB LD matrices previously at https://alkesgroup.broadinstitute.org/UKBB_LD are now 
available at s3://broad-alkesgroup-ukbb-ld/UKBB_LD/. Files can be downloaded for 
free as part of the AWS Open Data Program."

I suggest updating the create_finemapper_jobs.py script to reflect this

**Comment by omerwe** [comment] 2023-04-21 21:35
@nievergeltlab Thanks for reminding me that I needed to update the UKB regions file to point to the new files location. I just did, can you please git pull and let me know if the problem is resolved?

**Comment by omerwe** [comment] 2023-04-30 11:37
Hi, closing this issue for now, please reopen it if the problem persists. Thanks!

**Closed by omerwe** 2023-04-30 11:37 UTC
