### ISSUE TITLE
LD file derived from a plink file are wrong

### ISSUE THREAD

**Issue by came203** [omerwe/polyfun#63] opened 2021-09-23 10:52 UTC
Hi Omer,
very nice package, and very easy to use.
However, I found a problem when constructing the LD matrix from a BED file (I use a subsample of UKB).
SuSie runs fine using the wrapper function, but FINEMAP crashes when reading in the LD file.
I found out that in the finemap.ld file, several values are > 1 and there are values in the diagonal that are != 1.
I'm using 353 SNPs in the calculation.

> t<-as.matrix(fread("finemap.ld"))
> table(t>1)

 FALSE   TRUE 
124597     12 

> table(diag(t)!=1)

FALSE  TRUE 
  341    12 

> diag(t)<-1
> table(t>1)

 FALSE   TRUE 
124607      2 

Those values are all very close to 1 (mostly 1.00001), so I think it's just a matter of rounding, but it completely breaks the workflow. I'm using the conda polyfun environment, so there shouldn't be any compatibility issues. I think it's strange, because in the compute_ld_plink function, you set ld_diag[np.isclose(ld_diag, 0.0)] = 1

It is probably a very simple fix. In addition, why doesn't SuSIe check this?

Best wishes
Rainer

I'm attaching my finemap.ld as finemap.txt here
[finemap.txt](https://github.com/omerwe/polyfun/files/7216992/finemap.txt)

**Comment by omerwe** [comment] 2021-09-24 13:00
Hi, thanks for the bug report!

To debug this, I'll need a reproducible example. Can you reproduce this example using the example plink files provided with PolyFun? If not, do you think you could find some plink files that you're allowed to share with me, and that will allow me to reproduce this behavior? Please feel free to send the files to oweissbrod@hsph.havard.edu.

Thanks,

Omer

**Comment by omerwe** [comment] 2022-02-23 20:57
Thanks @jdblischak,

Just to make sure I understand: Does this happen when loading a .npz file from the cache dir? I guess it means that the .npz files sometimes lose accuracy, so that the diagonal becomes approximately but not exactly equal to 1.0? 

I guess one (imperfect) option would be to manually turn the diagonal into 1.0, though who knows what other troubles this could lead to...

**Comment by jdblischak** [comment] 2022-02-23 21:21
> Just to make sure I understand: Does this happen when loading a .npz file from the cache dir?

Correct. For the initial run when the new LD matrix file is created, the fine-mapping completes successfully. It's only when trying to re-load the LD matrix on a subsequent run that this check fails. This makes it difficult to try new settings or troubleshoot an unrelated error, because each time the LD matrix has to be re-created, which is the main bottleneck.

> I guess it means that the .npz files sometimes lose accuracy, so that the diagonal becomes approximately but not exactly equal to 1.0?

Agreed. That is a potential explanation. But for some reason all the of 3 MB regions that you created are fine.

> I guess one (imperfect) option would be to manually turn the diagonal into 1.0, though who knows what other troubles this could lead to...

My colleague suggested trying the exact same thing, so it can't be too crazy of an idea :-)

**Comment by omerwe** [comment] 2022-02-23 21:32
Well, you can fill the diagonal with lines with `np.fill_diagonal(R, 1.0)`.

Another option is to prevent converting the float representation from 64bit to 32bit (remove the `.astype(np.float32)` in: https://github.com/omerwe/polyfun/blob/a9a2274906ef0737a48c909ba0c86d03272a4833/finemapper.py#L207).



I would have tested these two options, but I don't have a reproducible example. For some reason I never had these issues when I worked with the UKBB LD matrices. If you don't mind trying these two options and see if they seem to help (and generate the same results as the non-cached run), I'm happy to modify the code accordingly.

Thanks!

**Comment by mkoromina** [comment] 2022-03-01 16:25
Hi @omerwe and @jdblischak, just a brief message to ask you whether you have recommendations for this issue as well. All the loci to be fine-mapped are successfully fine-mapped when I am using the UKB LD precomputed matrices (as stated in the wiki page). However,  as soon as I use plink files in the --geno flag, run polyfun-susie and then try to use the produced LD matrices (in the LD cache dir), it is not working hinting that the derived LD files do not work... Any hint on what I could try to this end? Thank you very much!

**Comment by jdblischak** [comment] 2022-03-02 18:20
> All the loci to be fine-mapped are successfully fine-mapped when I am using the UKB LD precomputed matrices (as stated in the wiki page). However, as soon as I use plink files in the --geno flag, run polyfun-susie and then try to use the produced LD matrices (in the LD cache dir), it is not working hinting that the derived LD files do not work

@mkoromina I am having the exact same experience

> Another option is to prevent converting the float representation from 64bit to 32bit (remove the .astype(np.float32) in:

@omerwe I tested this potential solution. Unfortunately it had no effect, so the error was still generated. The md5 checksums for the results file and `.npz` files were identical, and the checksum was also the same for the `.gz` file after it was decompressed and piped to `md5sum`.

I noticed that conversion to `np.float32` was also done in a few other places. Do I need to update all of them for this to work?

https://github.com/omerwe/polyfun/blob/a9a2274906ef0737a48c909ba0c86d03272a4833/finemapper.py#L476-L477

https://github.com/omerwe/polyfun/blob/a9a2274906ef0737a48c909ba0c86d03272a4833/finemapper.py#L526

**Comment by jdblischak** [comment] 2022-03-02 19:55
**Update:** Replacing all instances of `np.float32` with `sed -i 's/float32/float64/g' finemapper.py` fixed the error with reading the cached LD file

**Comment by mkoromina** [comment] 2022-03-02 21:04
Hi @jdblischak, thank you so much for looking into this so quickly! Silly question: would we need update our conda environment and re-install polyfun or can we somehow edit the finemapper.py script to do this?

**Comment by jdblischak** [comment] 2022-03-02 22:33
My PR #90 hasn't been reviewed/merged yet. If you'd like to try it out, you can fetch the code from my fork by running the following Git commands:

```
git remote add jdblischak https://github.com/jdblischak/polyfun.git
git fetch jdblischak
git checkout jdblischak/read-cached-ld
```

**Closed** 2022-03-04 10:23 UTC

**Comment by omerwe** [comment] 2022-03-04 10:48
Hi, I just accepted the PR. Please git pull the latest version, hopefully it will fix this issue!

**Comment by mkoromina** [comment] 2022-03-04 17:10
hi @omerwe and @jdblischak thank you both so much for your prompt replies and look into these matters! so to sum up, shall I guide to my polyfun directory and simply type: **git pull** ? Silly question but just to be safe: should I need to reactivate my conda environment after typing git pull?

**Comment by jdblischak** [comment] 2022-03-04 17:49
> shall I guide to my polyfun directory and simply type: git pull ?

If you haven't ran any of the Git commands above, then yes, a simple `git pull` should be sufficient. If you want to be sure, you can run `git log -n 1` and `git branch`. You should see the following:

> should I need to reactivate my conda environment after typing git pull?

No. PolyFun is not a package. It is a collection of Python scripts. Once you download them with `git pull`, you can use them right away.
